### ISSUE TITLE
Add a twitter app for the vertx-pac4j-demo to use

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j-demo#31]
Currently vertx-pac4j-demo uses the play-pac4j twitter app just to get things working

Add a twitter app and point the vertx-pac4j-demo application to it

**Comment by leleuj** [comment]
Be careful when reusing OAuth applications: identity providers check callback urls in very different ways and may reject them if the port is different for example (for Play, it's the port: 9000).

**Comment by millross** [comment]
The play one does actually work for this (despite being on a different port) so I can use the play one for temporary troubleshooting but it looks a bit silly calling a twitter application which displays "play-pac4j-demo" from a demo application called "vertx-pac4j-demo", hence raising this issue.
