### ISSUE TITLE
mvn vertx:runMod BUILD FAILURE No plugin found for prefix 'vertx' 

### ISSUE THREAD

**Issue by plutext** [pac4j/vertx-pac4j-demo#32]
As per the instructions, I executed mvn vertx:runMod

I got a BUILD FAILURE:
[ERROR] No plugin found for prefix 'vertx' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories

How to fix?

I installed https://github.com/vert-x/vertx-maven/tree/master/plugin

and added to .m2/settings.xml

  <pluginGroups>
    <pluginGroup>io.vertx</pluginGroup>
  </pluginGroups>

Is this correct?

**Comment by millross** [comment]
Fixed instructions as per issue #14
