### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by mavencode01** [pac4j/vertx-pac4j-demo#37]
I just tried the demo and found out the logout feature won't work also.

You can try click on the logout button and hit the browser back button. You still can access the protected page.

I reported the sample issue here: https://github.com/pac4j/play-pac4j/issues/119

**Comment by millross** [comment]
Sure this isn't browser caching of the response? Did you refresh following the back button to ensure that it's genuinely accessing the protected page?

**Comment by millross** [comment]
If you have tried with a refresh and proved it's not logging out, then please provide step by step start to finish including the refresh, also browser details (though if happening in play-pac4j too it may really be a pac4j core issue).

**Comment by mavencode01** [comment]
@millross Yup, I refreshed the browser after logout and hit the back button, still has access to the protected page. I'm using the latest keycloak version 2.0.0.Final

**Comment by millross** [comment]
I know nothing about key cloak and the vertx-pac4j implementation is irrelevant to it. 

How do you repeat the problem in the existing vertx-pac4j-demo?

**Comment by millross** [comment]
(I want to know what client you log in with, what you see at each stage and then again after the back button).

**Comment by millross** [comment]
(because I can't replicate your problem using e.g. the form authentication client).

**Comment by mavencode01** [comment]
I'm testing with the  OpenID Connect client

**Comment by millross** [comment]
Step by step please, as requested, including what you see at each stage.

**Comment by millross** [comment]
When I hit back using OIDC client (and I do this twice following logout) I get to a cached version of this page. Refresh then forces a re-authentication (which I can see because I'm asked about offline access). This is exactly what I would expect to happen.

**Comment by mavencode01** [comment]
1. Run the demo vertx-pac4j-demo-master
2. Open your browser - private mode to be sure.
3. Login via the OpenID Connect client
4. It redirects you to your provider and after login, redirects you to the protected page of your application
5. Go back to home page, and logout
6. Refresh the browser after logout as many times possible
7. Hit the browser back button, you should still have access to the protected page

**Comment by millross** [comment]
You're refreshing at the wrong time, your back will still give you a cached version of the page. You don't still have access, your browser has cached it. When on the protected page, hit refresh.

**Comment by millross** [comment]
(in the real world rather than the toy demo project we would set cache control headers, but different browsers apply those to the back button cache differently anyway, so even that's potentially insufficient)

**Comment by mavencode01** [comment]
I actually refreshed on every step to make sure it's not the cached version ;-)

**Comment by millross** [comment]
I went through the steps above and I could not replicate the problem. Once I saw the "OIDC post-login" page I refreshed and I was provably re-authenticated. Cannot therefore reproduce the issue.

**Comment by mavencode01** [comment]
I'm using keycloak do I don't get the offline access...just returns my profile again wihout loggin in.

Qq - is there a way I could force the login again before showing offline access after logout ?

**Comment by millross** [comment]
Specifically, to go step by step

Run current vertx-pac4j-demo (which hasn't changed in some time so I assume you're running the same one)
Using google Chrome
Hit http://localhost:8080
Click on "protected by OIDC connect" link
See a page saying "vertx-pac4j-demo" would like to... (part of the authentication process)
Click "Allow"
See I'm redirected to http://localhost:8080/oidc/index.html#
Click "Back" link so my profile will show in the main page
See my profile showing at the bottom of main page
Click "Logout" link
Watch profile disappear from bottom of main page
Click browser back button (see the same)
Click browser back button again
See I'm back at http://localhost:8080/oidc/index.html# with a profile showing because this was served from cache
Refresh now - see the request for permissions again

I don't know what keycloak is by the way, but it may be caching the fact you're logged in server side. If you're already logged in on the far side provider you will log in silently under pac4j, just as you do when using Facebook login for example

To force login again, you need to force logout from the Keycloak provider.

**Comment by millross** [comment]
and for OIDC I'm not sure that someone hooking into an OIDC provider should force logout from the provider, it shouldn't - for example - for oAuth2.

**Comment by millross** [comment]
Aha OIDC sits on top of OAuth2, that implies that logging out of the vertx-pac4j-demo shouldn't log you out of that provider. Your web client will keep you logged into that provider. That's kind of the point of single sign on.

**Comment by millross** [comment]
I also thought you were using vertx-pac4j-demo which doesn't communicate with a keycloak provider.

**Comment by mavencode01** [comment]
> Aha OIDC sits on top of OAuth2, that implies that logging out of the vertx-pac4j-demo shouldn't log you out of that provider

So the logout is useless here, hitting the back button will still allow access to the protected page.

> I also thought you were using vertx-pac4j-demo which doesn't communicate with a keycloak provider.

I updated the code to talk to my keycloak provider

**Comment by mavencode01** [comment]
Is there a way to sort of do a federated logout ?

**Comment by millross** [comment]
As I said I don't know key cloak. You'll need to raise that requirement with the pac4j core guys. This appears not to be an issue with the vertx wrapper round those core libs.

**Comment by mavencode01** [comment]
Ok...thanks @millross

**Comment by millross** [comment]
>>> So the logout is useless here, hitting the back button will still allow access to the protected page.

Not quite: if following logout you specifically log out of the provider by hitting whatever logout url it offers, then you will. All the oAuth2 style logout does is logs you out of this system.

If you want to trigger federated logout without core pac4j changes then you will need to add your own handler for the logout url which firstly triggers logout from the provider by hitting its logout url then hits the logout handler in your application. In the case of vertx that would be chained handlers on the same url

**Comment by millross** [comment]
If it doesn't make sense for pac4j to offer the global logout I'm happy (if you set up a simple demo project based on vertx-pac4j-demo and shared on github) to help you build the "global logout" approach I outline above. But I'm not convinced it's generally desirable to do so - imagine if you click Logout on say Strava which you log into via Facebook's oAuth authentication, and logging out of Strava also logs you out of Facebook and every other application you authenticate with via Facebook? I'm not sure most users want that :)

**Comment by mavencode01** [comment]
@millross I'm really new with Keycloak and OpenID Connect stuff...so maybe am looking at the problem from a wrong direction. 

If you got a financial application and you really want to secure it with OpenID connect, how will you then logout securely from the application so next time, the user will have to login again?

**Comment by millross** [comment]
Then you would need to force a global logout. But remember the main reason these identity management systems get used is to enable single sign on (log into one web app, log into all which are using the same system). 

So forcing a global logout from one application is not the norm, but it is still possible if the provider offers a url to which you can redirect on logout and which redirects to another url of your choice to complete the local logout (remember you need to clear both "local server" and "provider server" sessions". This is all managed within the browser - for OAuth 2 when you hit a url if not already logged into the local system you're redirected to the provider server. However, if already logged into that you will be redirected back to your application without further challenge but with information about the fact you're already authenticated (so you won't be challenged). If not, you will be challenged there. 

If you only have one application it's easy to add an endpoint (even without stuff being built into pac4j) that redirects to your auth provider's logout page which will hopefully redirect back so you can be logged out locally. And if only using one application it makes sense to go down that route, but if only using one application, why use an external authenticator at all? It's probably easier to hook in a simple local authenticator instead.

**Comment by millross** [comment]
http://openid.net/specs/openid-connect-session-1_0.html#RPLogout shows how you'd build the approach in your web app - basically you have one endpoint for logout which lets you choose between global and local. If local you redirect directly to an endpoint using the LogoutHandler we already have. For the global case you redirect to the auth provider's logout url, but supply the local logout handler endpoint to it as a parameter so that following global logout you will be logged out locally.

**Comment by mavencode01** [comment]
The global case is exactly my use case for my micro-services. Is there any plan to support this ?

**Comment by millross** [comment]
Looking at the issue you commented on for pac4j, maybe, but it's easy to build out yourself. Though I'm not sure why you'd use OIDC for microservices (it rather relies on passing cookies round for example, and retaining a persistent session), it's aimed at Web UI applications (not sure how it applies in mobile apps) primarily where browsers will store cookie info.

**Comment by mavencode01** [comment]
Isn't direct client for web services authentication and you pass the bearer token to your service?

**Comment by millross** [comment]
I see where you're coming from so you auth through the redirect mechanism then pass the token to your service calls - that makes sense. However, are you going to have more than one application sitting atop those services?

**Comment by millross** [comment]
If you do, then if you trigger global logout, what will happen is as follows:-

Imagine 3 applications A, B, C all calling your services with a bearer token obtained by logging into your provider once. That bearer token will be stored by all three applications.

Log out of A (which in turn logs out of provider). B and C remain logged in using the same bearer token to call your services. Are you really more secure?

**Comment by mavencode01** [comment]
yeah but if you logout of A (which in turn logs out of provider) that should be a federated logout ?

**Comment by millross** [comment]
That won't happen. Any web app will retain the principal in their session some time. Unless OIDC itself offers a protocol for calling back into applications a la CAS, then B and C are ignorant of the logout behind the scenes until the user's session expires on them. The alternative is to not store in the session but authenticate every call via hitting the backend provider server.

**Comment by millross** [comment]
But as far as I know there is no plan for the callback-based federated logout from OIDC.

**Comment by mavencode01** [comment]
Yes you right...will still have to do some research on this but it's not a bad idea if you logout of A and the other services are logged out 


> Log out of A (which in turn logs out of provider). B and C remain logged in using the same bearer token (because they'll keep your principal in their respective sessions) and try to call your services, but now presumably fail behind the scenes because they're no longer authorised. That doesn't feel like what you'd want to me.

**Comment by millross** [comment]
It's not automatically a bad idea, but it all depends on use-case and what you expect the users to expect. The page I linked to takes the line that you have to offer global logout but the user has to be able to choose not to log out globally. That rather feels like a logout url which redirects to another page asking if you want to do global or local and then working from that choice. I'll wait and see what comes out of the discussions on the core pac4j issue you commented on, but you can definitely implement that in vert.x on top of vertx-pac4j (by offering a custom handler on the logout url).

**Comment by mavencode01** [comment]
Yup...will implement it myself for now - Thanks!

**Comment by millross** [comment]
If using vert.x if you want to dummy up a trivial version and share on github, I'm happy to try and help out if you run into problems. I know vert.x better than I know authentication mechanisms :)

**Comment by mavencode01** [comment]
Hhahaha...ofcourse I don't mind ;-)

**Comment by leleuj** [comment]
pac4j libs (like vertx-pac4j) propose a local logout, which will work locally but won't seem to work if the user is still authenticated at the central server, because he will be automatically and transparently re-authenticated. The problem happens for most identity providers, even for Facebook. There is an issue: https://github.com/pac4j/pac4j/issues/54 regarding that point we'll try to tackle for version 2.0, except if someone has time to work on that and propose something.
Following @millross recommendation, you can certainly implement something in Vertx for now, waiting for a general solution.
