### ISSUE TITLE
Cannot run demo from https://github.com/pac4j/vertx-pac4j-demo

### ISSUE THREAD

**Issue by eugenedruy** [pac4j/vertx-pac4j-demo#9]
According to the instructions at https://github.com/pac4j/vertx-pac4j-demo
I cloned the git repo to my machine (Cent  OS 6.6), built and tried to run .
However the demo module cannot be found 
------------------------------------------------------------------------------------------------------------------------------
[eugenedroi@localhost target]$ vertx runMod org.pac4j~vertx-pac4j-demo~1.0.0-SNAPSHOT
Succeeded in deploying module 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in Java verticle 
org.vertx.java.platform.PlatformManagerException: Module org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT not found in any repositories
	at org.vertx.java.platform.impl.DefaultPlatformManager.getModule(DefaultPlatformManager.java:1451)
	at org.vertx.java.platform.impl.DefaultPlatformManager.doInstallMod(DefaultPlatformManager.java:1440)
	at org.vertx.java.platform.impl.DefaultPlatformManager.deployModuleFromFileSystem(DefaultPlatformManager.java:1270)
	at org.vertx.java.platform.impl.DefaultPlatformManager.access$1300(DefaultPlatformManager.java:59)
	at org.vertx.java.platform.impl.DefaultPlatformManager$13.run(DefaultPlatformManager.java:464)
	at org.vertx.java.platform.impl.DefaultPlatformManager$15.run(DefaultPlatformManager.java:489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
------------------------------------------------------------------------------------------------------------------------------
Same if I'm trying to run demo through maven
------------------------------------------------------------------------------------------------------------------------------
[eugenedroi@localhost vertx-pac4j-demo]$ pwd
/home/eugenedroi/workspace/vertx-pac4j-demo
[eugenedroi@localhost vertx-pac4j-demo]$ mvn vertx:runMod -Prest
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Project - vertx-pac4j-demo 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vertx-maven-plugin:2.0.11-final:runMod (default-cli) @ vertx-pac4j-demo ---
[INFO] CTRL-C to stop server
Sep 14, 2015 3:02:28 PM org.pac4j~vertx-pac4j-demo~1.0.0-SNAPSHOT-org.pac4j.vertx.Pac4jDemo-570082342
SEVERE: Exception in Java verticle
org.vertx.java.platform.PlatformManagerException: Module org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT not found in any repositories
	at org.vertx.java.platform.impl.DefaultPlatformManager.getModule(DefaultPlatformManager.java:1449)
	at org.vertx.java.platform.impl.DefaultPlatformManager.doInstallMod(DefaultPlatformManager.java:1438)
	at org.vertx.java.platform.impl.DefaultPlatformManager.deployModuleFromFileSystem(DefaultPlatformManager.java:1268)
	at org.vertx.java.platform.impl.DefaultPlatformManager.access$1300(DefaultPlatformManager.java:57)
	at org.vertx.java.platform.impl.DefaultPlatformManager$12.run(DefaultPlatformManager.java:462)
	at org.vertx.java.platform.impl.DefaultPlatformManager$14.run(DefaultPlatformManager.java:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
------------------------------------------------------------------------------------------------------------------------------
This message pops up for both stateful and stateless runs. I have vertx 2.1.6 installed
The demo depends on 2.1.5. Even if I change dependency to 2.1.6 I still see the same
Trying to connect to http://localhost:8080/ hangs
Is there anything I might be missing?

**Comment by millross** [comment]
I'm porting vertx-pac4j (and the demo) to vert.x 3 so not familiar with the vert.x 2 version of this code but it looks to me as though the vertx-pac4j zip module isn't deployed to any maven repositories in its build (although the jar is), meaning that you would have to download it and install it manually (as a workaround). 

An alternative approach would be to build vert.x-pac4j 1.1 from source (it's tagged and branched on github) using mvn install, which should put it into your local maven repo (which will then be scanned by the vert.x module installer). If you use the branch, you will need to change the version of the module to 1.1.1-SNAPSHOT.

Jérôme might have some additional ideas on this, in case there's something I'm missing.

**Comment by leleuj** [comment]
You must use the release version: 1.1.0 (and not 1.1.0-SNAPSHOT): http://search.maven.org/#search%7Cga%7C1%7Cvertx-pac4j

**Comment by millross** [comment]
I stand corrected, the zip is in maven.

**Comment by eugenedruy** [comment]
OK, thanks for your replies
Eventually I managed to make it work
However it doesn't work "out of the box"
To make it work I had to change 
------------------------------------------------------------------------------------------------------------------------------------------
        container.deployModule("org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT",
                container.config().getObject("pac4jManager"));
to 
        container.deployModule("org.pac4j~vertx-pac4j-module~1.1.0",
                container.config().getObject("pac4jManager"));
(line 34 at)
https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/Pac4jDemo.java
------------------------------------------------------------------------------------------------------------------------------------------
and also to avoid invalid logger warning I had to add 
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j-api.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>${slf4j-api.version}</version>
    </dependency>
into pom.xml 
I think because busMod of org.pac4j~vertx-pac4j-module~1.1.0 comes with slf4j-api jar only

**Comment by leleuj** [comment]
It's a bit strange because I remember doing the test and it worked out of the box: what's your environment? Vertx version? OS?

**Comment by eugenedruy** [comment]
If you take a look mentioned in my previous post
(https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/Pac4jDemo.java)
you'll see the lines 34,35  
        container.deployModule("org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT",
                container.config().getObject("pac4jManager"));
which causes exactly the problem you recommended to fix
If you clone/download the demo and build it again you should be able to replicate the problems I encountered
Unless I've been experimenting with wrong repo or missing anything...

**Comment by daus-salar** [comment]
I had the same issue and the fix also worked for me. 

@leleuj: May be you had the snapshot build `org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT` in your local maven repository while you were testing the demo.
You can remove them with

    mvn clean 
    mvn dependency:purge-local-repository -DsnapshotsOnly=true -DmanualInclude=org.pac4j:vertx-pac4j-module

**Comment by leleuj** [comment]
You must be right: I likely have the SNAPSHOT dependency in my local repository.

The release version must be used. I just fixed the issue: https://github.com/pac4j/vertx-pac4j-demo/commit/a38869ecc79f1823898a66f4d77e56d9a11e1062
